package net.runelite.client.plugins.clueitems;

import com.google.common.collect.ImmutableSet;
import static net.runelite.api.ItemID.*;

import java.util.Set;
import java.util.function.Function;


public enum ClueItemTier
{
	NONE(ImmutableSet.of()),
	BEGINNER(ImmutableSet.of(BRONZE_AXE, CHEFS_HAT, GOLD_NECKLACE, GOLD_RING, LEATHER_BOOTS, RED_CAPE)),
	EASY(ImmutableSet.of(AIR_TIARA, BLACK_AXE, BLACK_CAPE, BLACK_PLATEBODY, BLUE_ROBE_TOP, BLUE_WIZARD_HAT, BLUE_WIZARD_ROBE, BODY_TIARA, BRONZE_2H_SWORD, BRONZE_AXE, BRONZE_CHAINBODY, BRONZE_DAGGER, BRONZE_FULL_HELM, BRONZE_PLATELEGS, BRONZE_SPEAR, COIF, CREAM_ROBE_TOP, DESERT_SHIRT, EMERALD_AMULET, EMERALD_RING, GOLD_NECKLACE, GOLD_RING, GREEN_BOOTS, GREEN_HAT, GREEN_ROBE_BOTTOMS, GREEN_ROBE_TOP, HAM_BOOTS, HAM_ROBE, HARDLEATHER_BODY, IRON_CHAINBODY, IRON_FULL_HELM, IRON_KITESHIELD, IRON_MED_HELM, IRON_PLATEBODY, IRON_PLATELEGS, IRON_PLATESKIRT, IRON_SCIMITAR, IRON_WARHAMMER, LEATHER_BOOTS, LEATHER_CHAPS, LEATHER_COWL, LEATHER_GLOVES, LONGBOW, MITHRIL_PICKAXE, OAK_LONGBOW, OAK_SHORTBOW, PINK_ROBE_TOP, PINK_SKIRT, RUBY_RING, SAPPHIRE_AMULET, SAPPHIRE_NECKLACE, SAPPHIRE_RING, STAFF_OF_WATER, STAFF, STEEL_AXE, STEEL_FULL_HELM, STEEL_LONGSWORD, STEEL_MACE, STEEL_MED_HELM, STEEL_PICKAXE, STEEL_PLATEBODY, STEEL_PLATESKIRT, STUDDED_BODY, STUDDED_CHAPS, TIARA, TURQUOISE_ROBE_BOTTOMS, WHITE_APRON)),
	MEDIUM(ImmutableSet.of(TEAM1_CAPE, ADAMANT_BOOTS, ADAMANT_DAGGER, ADAMANT_FULL_HELM, ADAMANT_HALBERD, ADAMANT_MED_HELM, ADAMANT_PLATEBODY, ADAMANT_PLATELEGS, ADAMANT_PLATESKIRT, ADAMANT_SQ_SHIELD, ADAMANT_SWORD, ADAMANT_WARHAMMER, AMULET_OF_POWER, BLUE_BOOTS, BLUE_DHIDE_BODY, BLUE_DHIDE_VAMB, BONE_DAGGER, BRONZE_FULL_HELM, BRONZE_SQ_SHIELD, BROWN_APRON, BRUISE_BLUE_SNELM, DIAMOND_RING, GREEN_DHIDE_BODY, GREEN_DHIDE_CHAPS, GREEN_HAT, GREEN_ROBE_TOP, HARDLEATHER_BODY, IRON_2H_SWORD, IRON_MED_HELM, IRON_PICKAXE, LEATHER_BOOTS, LEATHER_GLOVES, MAPLE_LONGBOW, MAPLE_SHORTBOW, MITHRIL_CHAINBODY, MITHRIL_FULL_HELM, MITHRIL_MED_HELM, MITHRIL_BOOTS, MITHRIL_PLATEBODY, MITHRIL_PLATELEGS, MITHRIL_PLATESKIRT, MITHRIL_SCIMITAR, MYSTIC_GLOVES, MYSTIC_ROBE_BOTTOM, PURPLE_GLOVES, RING_OF_DUELING1, RING_OF_DUELING2, RING_OF_DUELING3, RING_OF_DUELING4, RING_OF_DUELING5, RING_OF_DUELING6, RING_OF_DUELING7, RING_OF_DUELING8, RING_OF_FORGING, RING_OF_LIFE, RUBY_AMULET, SAPPHIRE_AMULET, SILVER_SICKLE, SNAKESKIN_BOOTS, SNAKESKIN_CHAPS, STAFF_OF_AIR, STEEL_KITESHIELD, STEEL_LONGSWORD, STEEL_PLATEBODY, STEEL_SQ_SHIELD)),
	HARD(ImmutableSet.of(RUNE_HERALDIC_HELM, RUNE_SHIELD_H1, AMULET_OF_GLORY, ADAMANT_2H_SWORD, ADAMANT_SQ_SHIELD, AMULET_OF_GLORY, AMULET_OF_POWER, AMULET_OF_STRENGTH, BLUE_DHIDE_BODY, BLUE_DHIDE_CHAPS, BLUE_DHIDE_VAMB, BONE_SPEAR, ANCIENT_CROZIER, ARMADYL_CROZIER, BANDOS_CROZIER, GUTHIX_CROZIER, SARADOMIN_CROZIER, ZAMORAK_CROZIER, DIAMOND_BRACELET, DIAMOND_RING, ELEMENTAL_SHIELD, FIRE_BATTLESTAFF, BLACK_HEADBAND, BLUE_HEADBAND, BROWN_HEADBAND, GOLD_HEADBAND, GREEN_HEADBAND, PINK_HEADBAND, RED_HEADBAND, WHITE_HEADBAND, IRON_PLATEBODY, MITHRIL_PLATELEGS, MYSTIC_FIRE_STAFF, MYSTIC_HAT, MYSTIC_ROBE_TOP, RING_OF_LIFE, RUNE_AXE, RUNE_BOOTS, RUNE_FULL_HELM, RUNE_HALBERD, RUNE_PICKAXE, RUNE_PLATEBODY, RUNE_PLATELEGS, RUNE_SPEAR, RUNE_WARHAMMER, ANCIENT_STOLE, ARMADYL_STOLE, BANDOS_STOLE, ZAMORAK_STOLE, SARADOMIN_STOLE, GUTHIX_STOLE)),
	ELITE(ImmutableSet.of(AMULET_OF_GLORY, RUNE_HERALDIC_HELM, BARROWS_GLOVES, BLACK_DHIDE_CHAPS, BLACK_DHIDE_VAMB, BLACK_SALAMANDER, BLUE_DHIDE_VAMB, BOBS_BLACK_SHIRT, BOBS_BLUE_SHIRT, BOBS_PURPLE_SHIRT, BOBS_GREEN_SHIRT, BOBS_RED_SHIRT, CASTLE_WARS_BRACELET1, CASTLE_WARS_BRACELET2, CASTLE_WARS_BRACELET3, CLIMBING_BOOTS, COMBAT_BRACELET, DRAGON_BATTLEAXE, DRAGON_BOOTS, DRAGON_MED_HELM, DRAGON_NECKLACE, DRAGON_SPEAR, DRAGONSTONE_AMULET, DRAGONSTONE_RING, HOLY_BOOK, BOOK_OF_BALANCE, UNHOLY_BOOK, BOOK_OF_LAW, BOOK_OF_WAR, BOOK_OF_DARKNESS, GRANITE_SHIELD, HELM_OF_NEITIZNOT, LAVA_BATTLESTAFF, MAGIC_LONGBOW, MIND_SHIELD, ANCIENT_MITRE, ARMADYL_MITRE, BANDOS_MITRE, GUTHIX_MITRE, SARADOMIN_MITRE, ZAMORAK_MITRE, MYSTIC_ROBE_BOTTOM, PIRATE_BANDANA, PROSELYTE_HAUBERK, RED_DHIDE_CHAPS, RING_OF_FORGING, ROLLING_PIN, RUNE_BOOTS, RUNE_CROSSBOW, RUNE_KITESHIELD, RUNE_LONGSWORD, RUNE_PLATESKIRT, SEERCULL, SPLITBARK_BODY, SPLITBARK_LEGS, SPOTTED_CAPE)),
	MASTER(ImmutableSet.of(PHARAOHS_SCEPTRE, RING_OF_WEALTH, SLAYER_HELMET,  ABYSSAL_WHIP, AMULET_OF_GLORY, AMULET_OF_THE_DAMNED, ARCLIGHT, BANDOS_BOOTS, BANDOS_CLOAK, BANDOS_GODSWORD, BANDOS_PLATEBODY, BLACK_DHIDE_BODY, BLACK_DHIDE_CHAPS, BLACK_DHIDE_VAMB, BLACK_DRAGON_MASK, BLACK_BOATER, BLUE_BOATER, GREEN_BOATER, ORANGE_BOATER, PINK_BOATER, PURPLE_BOATER, RED_BOATER, WHITE_BOATER, BRINE_SABRE, BRYOPHYTAS_STAFF, BULL_ROARER, CAPE_OF_LEGENDS, CLIMBING_BOOTS, CRYSTAL_BOW, DEATH_TIARA, DRAGON_2H_SWORD, DRAGON_AXE, DRAGON_BATTLEAXE, DRAGON_CHAINBODY, DRAGON_DEFENDER, DRAGON_MED_HELM, DRAGON_PICKAXE, DRAGON_PLATESKIRT, DRAGON_SQ_SHIELD, FIRE_CAPE, FLARED_TROUSERS, HELM_OF_NEITIZNOT, IBANS_STAFF, MENAPHITE_PURPLE_HAT, MENAPHITE_PURPLE_ROBE, MENAPHITE_PURPLE_TOP, MYSTIC_ROBE_BOTTOM_DARK, MYSTIC_ROBE_TOP_DARK, NATURE_TIARA, OBSIDIAN_CAPE, PHARAOHS_SCEPTRE, RING_OF_WEALTH, RUNE_BOOTS, RUNE_PLATEBODY, SHADOW_SWORD, SLAYER_HELMET, SPINED_CHAPS, SPLITBARK_BODY, TOKTZKETXIL, TOKTZXILUL, ZAMORAK_FULL_HELM, ZAMORAK_GODSWORD, AHRIMS_HOOD, AHRIMS_ROBESKIRT, AHRIMS_ROBETOP, AHRIMS_STAFF, KARILS_COIF, KARILS_CROSSBOW, KARILS_LEATHERSKIRT, KARILS_LEATHERTOP, VERACS_HELM, VERACS_FLAIL, VERACS_BRASSARD, VERACS_PLATESKIRT, DHAROKS_GREATAXE, DHAROKS_HELM, DHAROKS_PLATEBODY, DHAROKS_PLATELEGS, TORAGS_HAMMERS, TORAGS_HELM, TORAGS_PLATEBODY, TORAGS_PLATELEGS, GUTHANS_WARSPEAR, GUTHANS_HELM, GUTHANS_PLATEBODY, GUTHANS_CHAINSKIRT));

	private final Set<Integer> items;

	ClueItemTier(Set<Integer> items)
	{
		this.items = items;
	}

	public static ClueItemTier highestEnabledTier(int itemId, Function<ClueItemTier, Boolean> isEnabled)
	{
		ClueItemTier clueItemtier = NONE;
		for (ClueItemTier tier : ClueItemTier.values())
		{
			if (isEnabled.apply(tier) && tier.items.contains(itemId))
			{
				clueItemtier = tier;
			}
		}
		return clueItemtier;
	}
}
